name: suzuki CI/CD   # 🚀 Название workflow (отображается в GitHub Actions)

on:
  push:
    branches: [ main ]     # ▶️ Запуск при push в main
  pull_request:
    branches: [ main ]     # ▶️ Запуск при pull request в main
  workflow_dispatch:        # ▶️ Возможность ручного запуска (Run workflow кнопка)

permissions:
  contents: write           # 🔐 Разрешаем workflow создавать теги и релизы

jobs:
  # =====================================================
  # 1️⃣ TEST — проверка проекта и установка зависимостей
  # =====================================================
  test:
    runs-on: ubuntu-latest   # 🧰 Запуск на виртуальной машине Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # 📦 Клонируем код репозитория

      - name: Debug – показать структуру проекта
        run: |                     # 🔍 Показываем структуру файлов для отладки
          echo "PWD:"
          pwd
          echo "Файлы в корне:"
          ls -la
          echo "Файлы в backend/:"
          ls -la backend || true
          echo "Файлы в backend/src/:"
          ls -la backend/src || true

      - name: Set up Python
        uses: actions/setup-python@v5   # 🐍 Устанавливаем Python
        with:
          python-version: '3.10'
          cache: 'pip'                  # 💾 Кэшируем зависимости

      - name: Install dependencies (backend)
        run: |                          # 📦 Устанавливаем зависимости, если есть requirements.txt
          if [ -f backend/requirements.txt ]; then
            echo "✅ Устанавливаю зависимости из backend/requirements.txt"
            pip install -r backend/requirements.txt
          else
            echo "⚠️ Файл backend/requirements.txt не найден — пропускаю установку"
          fi

      - name: Run simple test (backend)
        run: |                          # 🧪 Пробный запуск backend/src/app.py
          if [ -f backend/src/app.py ]; then
            echo "🚀 Запускаю backend/src/app.py"
            python backend/src/app.py
          else
            echo "⚠️ Файл backend/src/app.py не найден — пропускаю тест"
          fi

  # =====================================================
  # 2️⃣ DOCKER — сборка и публикация Docker-образа
  # =====================================================
  docker:
    runs-on: ubuntu-latest
    needs: test                        # ⛓️ Запуск только после успешного job test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3    # 🔐 Входим в DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6   # 🐳 Собираем и пушим Docker image
        with:
          context: ./backend                # 📂 Папка с Dockerfile
          file: ./backend/Dockerfile        # 📜 Сам Dockerfile
          push: true                        # 🚀 Публикуем на DockerHub
          tags: |                           # 🏷️ Присваиваем 2 тега
            ${{ secrets.DOCKERHUB_USERNAME }}/suzuki:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/suzuki:${{ github.run_number }}

  # =====================================================
  # 3️⃣ TELEGRAM — уведомление об успешной сборке
  # =====================================================
  telegram:
    runs-on: ubuntu-latest
    needs: docker                         # ⛓️ После Docker job
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master   # ✉️ Отправляем сообщение через бота
        with:
          to: ${{ secrets.TELEGRAM_TO }}        # 🆔 ID чата
          token: ${{ secrets.TELEGRAM_TOKEN }}  # 🔑 Токен бота
          message: |                            # 💬 Сообщение о релизе
            ✅ Новая версия выпущена!
            🐳 Docker-образ: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/suzuki
            📦 Тег: ${{ github.run_number }}
            👤 Инициатор: ${{ github.actor }}

  # =====================================================
  # 4️⃣ RELEASE — создание релиза на GitHub
  # =====================================================
  release:
    runs-on: ubuntu-latest
    needs: telegram                       # ⛓️ После уведомления Telegram
    permissions:
      contents: write                     # ✍️ Разрешаем создавать теги и релизы
    steps:
      - name: Checkout code
        uses: actions/checkout@v4         # 📥 Получаем код проекта

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2   # 🏷️ Создаём GitHub Release (версия 2!)
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ Передаём системный токен для прав
          tag_name: v${{ github.run_number }}  # 🏷️ Создаём тег по номеру сборки (v14, v15 и т.д.)
          name: Release ${{ github.run_number }} # 📛 Имя релиза
          body: |                               # 📄 Описание релиза
            ✅ Тесты пройдены
            🐳 Docker образ опубликован (latest и ${{ github.run_number }})
            📬 Уведомление отправлено в Telegram
