name: suzuki CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug: show repo tree
        run: |
          echo "PWD:"
          pwd
          echo "ROOT:"
          ls -la
          echo "backend/:"
          ls -la backend || true
          echo "src/:"
          ls -la src || true

      - name: Set up Python
        if: ${{ hashFiles('backend/requirements.txt') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies (backend)
        if: ${{ hashFiles('backend/requirements.txt') != '' }}
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run simple test (backend)
        if: ${{ hashFiles('backend/src/app.py') != '' }}
        working-directory: backend
        run: python src/app.py

      # Если у тебя тесты/линтер в другом месте или другой командой — добавь здесь отдельные шаги.

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/suzuki:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/suzuki:${{ github.run_number }}

  telegram:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Новая версия выпущена!
            Образ: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/suzuki
            Тег: ${{ github.run_number }}
            Инициатор: ${{ github.actor }}

  release:
    runs-on: ubuntu-latest
    needs: telegram
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            ✅ Тесты пройдены
            🐳 Docker образ опубликован (latest и ${{ github.run_number }})
            📬 Уведомление отправлено в Telegram
